---
version: '3.7'
services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:preview
    environment:
      - TZ=Etc/UTC
      - EXTENSION_REPOS=["https://github.com/keiyoushi/extensions/tree/repo"]
    volumes:
      - ./data:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "4567:4567"
    restart: on-failure:3
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Etc/UTC
    ports:
      - "8191:8191"
    restart: unless-stopped